### ISSUE TITLE
Getting TypeConverterNotFoundException for type class java.lang.Float

### ISSUE THREAD

**Issue by SindhuKonda** [Tickaroo/tikxml#100]
Public class Location{

    @Attribute(name = "latitude")
    Float latitude; 

    @Attribute(name = "longitude")
    Float longitude;
}

In **Location$$TypeAdapter**  at line
writer.attribute("latitude", config.getTypeConverter(java.lang.Float.class).write(value.latitude));

getting following exception **com.tickaroo.tikxml.TypeConverterNotFoundException: No TypeConverter found for type class java.lang.Float. You have to add one via TikXml.Builder().addTypeAdapter()**

**Comment by WeaponMan** [comment]
Yes, you do or you can use Double with builtin TypeConverter.

**Comment by sockeqwe** [comment]
Uh, unfortunately I can't remember all the deatils, but I think we decided
to not support float because it is hard ro parse floats effectively without
running into rounding errors.

Maybe its time to revisit thid

Juat use double. (Btw. If value can't be null then use double rather than
Double).


SindhuKonda <notifications@github.com> schrieb am Mi., 19. Sep. 2018, 08:25:

**Comment by SindhuKonda** [comment]
Thank you for quick response.
