### ISSUE TITLE
annotation with version 0.8.15 not found in maven central, only 0.8.13

### ISSUE THREAD

**Issue by maxlord** [Tickaroo/tikxml#115]

**Comment by sockeqwe** [comment]
sorry about the inconvenience. Something in our publishing pipeline seems to be broken. In the meantime you can simply stick with 0.8.13 for annotation artifact only. 0.8.13 annotation works with 0.8.15 of the rest of tikxml.

**Comment by maxlord** [comment]
Project written in Kotlin. When i use 0.8.13 for annotation artifact, type adapters not generated.

i use settings
`
configurations.all {
	resolutionStrategy.force "com.tickaroo.tikxml:annotation:0.8.13"
}
`

**Comment by tadfisher** [comment]
That last one is happening because `processor-common` is being published as the `processor` artifact:

```
processor-0.8.16-SNAPSHOT
├── com
│   └── tickaroo
│       └── tikxml
│           └── processor
│               ├── converter
│               │   ├── AttributeConverterChecker.class
│               │   ├── ConverterChecker.class
│               │   └── PropertyElementConverterChecker.class
│               ├── ProcessingException.class
│               └── utils
│                   ├── ElementExtensionsKt.class
│                   ├── ElementExtensionsKt$getSuperClassesAndAllInterfaces$1.class
│                   ├── TypeMirrorExtensionKt.class
│                   └── TypeMirrorExtensionKt$WhenMappings.class
└── META-INF
    ├── MANIFEST.MF
    └── processor-common.kotlin_module
```

I would highly suggest moving to the builtin `maven-publish` plugin rather than using the publishing script.

**Comment by maxlord** [comment]
when will be published 0.8.15?

**Comment by sockeqwe** [comment]
I dont know why its not working. Does someone wants to help working on this?

Maxim Kuleshov <notifications@github.com> schrieb am Mi., 13. Feb. 2019,
21:22:

**Comment by maxlord** [comment]
https://search.maven.org/search?q=g:com.tickaroo.tikxml%20AND%20a:annotation&core=gav
i need version is 0.8.13. I need feature "keep field orders on serialize xml"

**Comment by cbruegg** [comment]
As a workaround, Jitpack can be used.

Add this to your root `build.gradle`:
```
allprojects {
	repositories {
		...
		maven { url 'https://www.jitpack.io' }
	}
}
```

Then you can declare the dependencies like this:
```
implementation 'com.github.Tickaroo.tikxml:annotation:0.8.15'
implementation 'com.github.Tickaroo.tikxml:core:0.8.15'
kapt 'com.github.Tickaroo.tikxml:processor-common:0.8.15'
kapt 'com.github.Tickaroo.tikxml:processor:0.8.15'
```

Jitpack pulls the dependencies straight from GitHub and builds them. Change `kapt` to `annotationProcessor` if you're not using Kotlin. I don't know why it's necessary to manually include the dependency on `processor-common` this way, but it works. Otherwise the build fails with a `ClassNotFoundException`.

**Comment by alexanderaltena** [comment]
Ah super!

I'm still using 0.8.13 now, so appreciate the update!!

With kind regards,

Alex


________________________________
Van: Christian Brüggemann <notifications@github.com>
Verzonden: woensdag 20 maart 2019 08:40
Aan: Tickaroo/tikxml
CC: alexanderaltena; Comment
Onderwerp: Re: [Tickaroo/tikxml] annotation with version 0.8.15 not found in maven central, only 0.8.13 (#115)


As a workaround, Jitpack can be used.

Add this to your root build.gradle:

allprojects {
        repositories {
                ...
                maven { url 'https://www.jitpack.io' }
        }
}


Then you can declare the dependencies like this:

implementation 'com.github.Tickaroo.tikxml:annotation:0.8.15'
implementation 'com.github.Tickaroo.tikxml:core:0.8.15'
kapt 'com.github.Tickaroo.tikxml:processor-common:0.8.15'
kapt 'com.github.Tickaroo.tikxml:processor:0.8.15'


Jitpack pulls the dependencies straight from GitHub and builds them. Change kapt to annotationProcessor if you're not using Kotlin. I don't know why it's necessary to manually include the dependency on processor-common this way, but it works. Otherwise the build fails with a ClassNotFoundException.

**Comment by cnnaji** [comment]
implementation 'com.tickaroo.tikxml:annotation:0.8.15'
    implementation 'com.tickaroo.tikxml:core:0.8.15'
    kapt 'com.tickaroo.tikxml:processor:0.8.15'
    implementation 'com.tickaroo.tikxml:retrofit-converter:0.8.15'

**Comment by cnnaji** [comment]
Hi Alex,
0.8.13 annotation does not work with 0.8.15 rest of tikxml I get -  'ERROR: Failed to resolve: com.tickaroo.tikxml:annotation:0.8.15' 

Here is what my related dependencies look like, what does yours look like?:
    implementation 'com.squareup.retrofit2:retrofit:2.5.0'
    implementation 'com.tickaroo.tikxml:annotation:0.8.13'
    implementation 'com.tickaroo.tikxml:core:0.8.15'
    kapt 'com.tickaroo.tikxml:processor:0.8.15'
    implementation 'com.tickaroo.tikxml:retrofit-converter:0.8.15'

**Comment by ivanstefko** [comment]
any updates on this? Currently I'm using v0.8.13 but there are some deprecated classes 
Warning:(7, 39) java: com.tickaroo.tikxml.typeadapter.NestedChildElementBinder in com.tickaroo.tikxml.typeadapter has been deprecated

**Comment by sockeqwe** [comment]
No uodate yet, but that didn't change in 0.8.15 . Its still marked as
deprecated ...

ivanstefko <notifications@github.com> schrieb am Do., 20. Juni 2019, 14:53:

**Comment by ivanstefko** [comment]
one more thing regarding to warning message of deprecated class used in TypeAdapter. In my project I have a lot of mentioned warnings. Is there any way how to avoid these warnings. Can I use some alternative for it?

Thanks,

**Comment by newmanw** [comment]
0.8.15 is still not available, why was this closed?
