### ISSUE TITLE
Question about usage

### ISSUE THREAD

**Issue by dionisi** [Tickaroo/tikxml#50]
Hi,

Is there any documentation where I can see how to use it? 
I found only documentation about xml -> java mapping which is quite impressive, but I get some errors when I try to use it.
Do I need to write TypeAdapter for every class?

If I try to create object in following way
`       TikXml parser = new TikXml.Builder().build();
        DataTable result = parser.read(Okio.buffer(Okio.source(is)), DataTable.class);`

I get the exception:
`com.tickaroo.tikxml.TypeAdapterNotFoundException: No TypeAdapter for class foo.bar.DataTable`

**Comment by sockeqwe** [comment]
You have to annotate  DataTable with @Xml etc. As described in the
documentation. Then the TikXml annotation processor generates the
TypeAdapter for DataTable. Are you sure that annotation processing runs?

You are instatiating and using Okio and TikXml correctly, but you are right
this part is missing in the documentation.

Your issue is that no TypeAdapter for DataTable has been generated. Eithe
because you haven't annotated your class Data Table with @Xml annotations
etc. or annotation processing doesnt run at all to generate the
TypeAdapter. do you usen maven or gradle?

dionisi <notifications@github.com> schrieb am Sa., 3. Dez. 2016, 20:35:

**Comment by dionisi** [comment]
Thanks for the prompt answer!
Somehow I missed to add the dependency apt 'com.tickaroo.tikxml:processor:0.8.5-SNAPSHOT' to my project. Now it runs at least with the simplest example.

Thank you,
Peter
