### ISSUE TITLE
Tag releases

### ISSUE THREAD

**Issue by evant** [Tickaroo/tikxml#69]
I know this isn't 1.0, but it would still be useful to tag versions. And also provide a changelog.

**Comment by sockeqwe** [comment]
Agreed although from public API point of view hasn't changed much since
open sourcing if I remember correctly (we just have added kotlin and
autovalue support). We have plans to do that in the future, also we have
plans to release 0.9.0 onwards (not only snapshots) some time end of
July... And a stable 1.0 version by end of summer.

Evan Tatarka <notifications@github.com> schrieb am Mi., 14. Juni 2017,
17:13:

**Comment by sockeqwe** [comment]
I just have published the first non-snapshot version `0.8.13`.

Changelog is the release section (`0.8.13` is pretty empty though)
