### ISSUE TITLE
Propsal for Annotations

### ISSUE THREAD

**Issue by sockeqwe** [Tickaroo/tikxml#8]
Our requirements to the parser:

1. Low memory usage
2. Polymorphism is a very important
3. Fast parsing. Since we are parsing huge xml documents (more than 3000 xml elements nodes) an annotation processing based solution for "type adapters"(mapping an xml element to the java class) will be implemented (adding a reflection based type adapter will be possible)
4. Our xml elements have a lot of attributes: `<element a="true" b="2015-12-15" />`. We need "type adapters" for attributes as well. However, I'm not sure if the same type adapters can be used for both, xml elements and xml element attributes. Maybe we need some kind of "type converter" as addition to "type adapters" for xml element attributes.
5. Compatibility to simple xml would be nice, but is not a requirement.

Ok, so I have written down a proposal for the annotation API. 

The proposal can be read here: https://github.com/Tickaroo/tikxml/blob/master/docs/AnnotatingModelClasses.md

 Some parts of the API are inconsistent, but I don't know how to do it better way yet. XML is such a ugly format.

Inconsistency (maybe you find some more inconsistencies not listed here):

1. Regarding polymorphism, it's a mix of using xml element name as java class property and java class type to resolve polymorphism.
2. Especially `@ChildElement` vs. `@ChildElementList` (list has an inline option while `@ChildElement` has none), but do we really need two annotations for the similar thing? Can we use `@ChildElement` on Lists, if yes, what about inlining?
3. `@PropertyElement` vs. `@TextContent` (plus `@Path`)

What do you think about the name of the annotations?

**Comment by Bodo1981** [comment]
Regarding the points of inconsistency:

1) maybe another solution is to expect, that xml tags are unique (e.g. <book> should always be mapped to a java class Book). if so you don´t have to specify all the ```TypMatcher``` and can search for a class with this name or annotated with this name. and if you have an xml document where <book> should be mapped to another class you could specify this with the ```TypMatcher``` as you already could with ```converter```

2) if possible you should only have one annotation ```@ChildElement```. the problem is here the ```inline```property. you could simple ignore it if the annotated field is not a collection or write an extra lint check not to use this property on other fields which are not a collection. but if this is not possible you have to use two annotation - simple xml is also using ```@Element``` and ```@ElementList````

3) first of all ```@Path```should work with both annotations. you could avoid ```@TextContent``` and use ```@PropertyElement```with an inline property but then only one ```@PropertyElement``` can be used with inline=true. so i think it would be ok to use both annotations also because of a better readability

**Comment by sockeqwe** [comment]
1. We need to know how to map from xml element name to java class, hence an additional annotation like `@TypeMatcher` is required. Furthermore, if you have classes annotated in a library and in the app itself, annotation processing runs during compiling the library. Then you include the compiled library into your app and annotation processing runs only on your android apps annotated classes. So this dynamic mapping from element name is not possible at runtime. The only way to do that at runtime is by using reflections, but its super slow to scan all classes to determine the xml element name.
2. Ok, we use only `@Element` for both, simple child elements and list of elements. Additionally we introduce `@InlineList` for inlining list of elements.
3. `@TextContent` applies on the current xml element whereas `@PropertyElement` applies on chile elements of the current element. Hence both are used for different use case and needed.

Additionally we also introduce a "mode" to write less annotations: `@Xml( mode = Mode.ANNOTATIONS_ONLY or Mode.COMMON_CASE) ` where `COMMON CASE` means, read primitive java types as xml attributes  (corresponds to annotating the field with `@Attribute`) and object as xml child elements (corresponds to annotating the field with `@Element`). So for the common case less annotations are required. However, in the common case we need a way to tell the parser to ignore a field. We could use java `transient` keyword. However, that might cause conflict with other tools. Therefore we will introduce `@IgnoreXml`.
